[package]
name = "hashers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = {path = "../utils"}

num = "0.4.1"
itertools = "0.10.0"
json = "0.12.4"
crypto-bigint = { version = "0.6.1" } 
strum = { version = "0.26", features = ["derive"] }
hex-literal = "1.0.0"
