[package]
name = "crypto-gui"
version = "0.1.0"
authors = ["Alexander"]
edition = "2021"
rust-version = "1.56"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 2

[dependencies]
eframe = "0.16.0" # Gives us egui, epi and web+native backends
lazy_static = "1.4.0"
serde = { version = "1", features = ["derive"], optional = true }
num = "0.4.0"
itertools = "0.10.0"
rand = "0.8.3"
getrandom = { version = "0.2", features = ["js"] }