[package]
name = "rngs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = {path = "../utils"}

num = "0.4.1"
itertools = "0.10.0"
getrandom = { version = "0.2", features = ["js"] }
json = "0.12.4"
primal = "0.3.0"
num-prime = "0.4.3"
strum = { version = "0.26", features = ["derive"] }