unknown    = !{ ANY }

signs    =  { "A" | "B" | "C" | "D" | "E" | "É" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "0" | "." | "," | ":" | "?" | "'" | "-" | "/" | "(" | ")" | "\"" | "=" | "+" | "@" | "[UNDERSTOOD]" | "[ERROR]" | "[INVITATION-TO-TRANSMIT]" | "[WAIT]" | "[END-OF-WORK]" | "[STARTING-SIGNAL]" } 
space    = { " " }
morse_passage = { (signs | space | unknown)+ }

